version: "3.8"

services:
  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: 1234
    restart: unless-stopped

  mongo_db:
    image: mongo:latest
    container_name: db_mongo
    ports:
      - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: books_db
    restart: unless-stopped

  postgresql_db:
    image: postgres:latest
    container_name: db_postgresql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: db_students_loans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    restart: unless-stopped

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

