version: "3.8"

services:
  db_mysql:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: 1234
    expose:
      - 3306
    restart: unless-stopped